apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: hello-world  
    spec:     # pod spec                  
      containers: 
      - name: hello-world 
        image: dockernikki/nodejs:latest
        ports:
        - containerPort: 3000
        
---
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: nodejs-service 
spec: 
  selector: 
    app: nodejs
  ports: 
  - protocol: TCP 
    port: 3000
    targetPort: 3000
    nodePort: 31000 
  type: NodePort 
